src: rename top-level bb imports to avoid oe-core/bitbake collision
While adding nativesdk-wic to buildtools-extended-tarball and using
it for bitbake build, it triggered the following failure:

	$ which wic
	path-to/buildtools.buildtools-extended-standalone-10.26.17.0/sysroots/x86_64-wrlinuxsdk-linux/usr/bin/wic

	$ bitbake core-image-minimal
	ERROR: Unable to parse Var <METADATA_BRANCH[:=]>
	Traceback (most recent call last):
	  File "oe-core/bitbake/lib/bb/data_smart.py", line 465, in expandWithRefs
	    s = __expand_python_regexp__.sub(varparse.python_sub, s)
	  File "oe-core/bitbake/lib/bb/data_smart.py", line 154, in python_sub
	    value = utils.better_eval(codeobj, DataContext(self.d), {'d' : self.d})
	  File "oe-core/bitbake/lib/bb/utils.py", line 489, in better_eval
	    return eval(source, ctx, locals)
	  File "Var <METADATA_BRANCH[:=]>", line 1, in <module>
	AttributeError: module 'oe' has no attribute 'buildcfg'

In order to avoid a namespace collision between the oe module in oe-core
and the bb module in bitbake, rename src/bb -> src/wic/bb, src/oe ->
src/wic/oe, rename oe to wic.oe, bb to wic.bb

After applying the patch to wic recipe locally, running the oe-selftest
wic case results in:

	$ oe-selftest -r wic
	...
	2026-04-28 20:00:03,230 - oe-selftest - INFO - SUMMARY:
	2026-04-28 20:00:03,230 - oe-selftest - INFO - oe-selftest () - Ran 95 tests in 7853.682s
	2026-04-28 20:00:03,230 - oe-selftest - INFO - oe-selftest - FAIL - Required tests failed (successes=87, skipped=1, failures=0, errors=7)

PS: the FAIL cases are about qemu related about `Permission denied on tap'

Reviewed-by: Trevor Woerner <twoerner@gmail.com>
Signed-off-by: Hongxu Jia <hongxu.jia@windriver.com>